# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f0eb50e9f25fbe2c489708422009f267ecec65fa3d5d64c740d1d829aa04383c49f8f6cf738b59fe9715219b92e47fbca00d1055f0c3cbfd4ba9a43cdfc55099

test:
  secret_key_base: 37ba28a88ecebd300e2abee15ce231baec1dcd3f22a1be3d1f146899bba09b968d41218fff37fe8fecc5e79182ce4e5e7dc69d0001b97f90aae5600f5fe46561

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
